# Generated by Django 5.0 on 2023-12-21 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnergyPlant",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("fuel_type", models.CharField(max_length=50)),
                ("technology", models.CharField(max_length=100)),
                ("set_type", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("capacity", models.FloatField(blank=True, null=True)),
                ("efficiency", models.FloatField(blank=True, null=True)),
                ("date_in", models.FloatField(blank=True, null=True)),
                ("date_retrofit", models.FloatField(blank=True, null=True)),
                ("date_out", models.FloatField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("volume_mm3", models.FloatField(blank=True, null=True)),
                ("dam_height_m", models.FloatField(blank=True, null=True)),
                ("storage_capacity_mwh", models.FloatField(blank=True, null=True)),
                (
                    "eic",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        size=None,
                    ),
                ),
                ("project_id", models.JSONField()),
            ],
        ),
    ]
