# Generated by Django 5.0 on 2023-12-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyplant",
            name="project_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
